# Generated by Django 4.2 on 2023-06-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=1)),
                ('bday', models.DateTimeField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('goalweight', models.IntegerField()),
                ('activity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_person', to='tracker.user')),
            ],
        ),
    ]
