# Generated by Django 4.2.2 on 2023-06-23 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_person_sex_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="user",
        ),
    ]
