# Generated by Django 4.2.2 on 2023-06-24 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_person_maintainance"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="type",
            field=models.CharField(default="cardio", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="food",
            name="calories",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="food",
            name="date",
            field=models.DateTimeField(default=datetime.date(2023, 6, 24)),
        ),
        migrations.AddField(
            model_name="food",
            name="meal",
            field=models.CharField(default="breakfast", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="sex",
            field=models.CharField(max_length=10),
        ),
    ]
