# Generated by Django 4.2.2 on 2023-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_exercise_calories_exercise_date_alter_food_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="goalcalorie",
            field=models.IntegerField(default=0),
        ),
    ]
