# Generated by Django 4.2.2 on 2023-06-26 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_person_goalcalorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="carbs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="food",
            name="cholesterol",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="food",
            name="protein",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="food",
            name="sodium",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="date",
            field=models.DateTimeField(default=datetime.date(2023, 6, 26)),
        ),
        migrations.AlterField(
            model_name="food",
            name="date",
            field=models.DateTimeField(default=datetime.date(2023, 6, 26)),
        ),
    ]
