# Generated by Django 4.2.2 on 2023-06-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracker",
            "0010_food_carbs_food_cholesterol_food_protein_food_sodium_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="sugar",
            field=models.IntegerField(default=0),
        ),
    ]
