# Generated by Django 4.2.2 on 2023-06-26 03:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0011_food_sugar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="food_item",
            new_name="name",
        ),
    ]
