# Generated by Django 4.2 on 2023-06-28 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_rename_food_item_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 6, 28)),
        ),
    ]
