# Generated by Django 4.2 on 2023-06-28 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_exercise_date_alter_food_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
