# Generated by Django 4.2 on 2026-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_exercise_date_alter_food_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fibre',
            field=models.FloatField(default=0),
        ),
    ]
