# Generated by Django 4.2 on 2026-05-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_fooddatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
