# Generated by Django 4.2 on 2026-05-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_delete_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fibre',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sugar',
        ),
    ]
