# Generated by Django 4.2 on 2026-05-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_food_cholesterol_remove_food_fibre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fibre',
            field=models.FloatField(default=0),
        ),
    ]
